### ISSUE TITLE
Unable to render jsx in observable

### ISSUE THREAD

**Issue by nerfpops** [garbles/yolk#111]
This code:

    let page = Rx.Observable.create(obs => {
        obs.onNext(<CustomerDashboard email="hey" />)
    })
    return (<div>{page}</div>)

Results in:

    [object Object]

Where CustomerDashboard is just a simple module that renders props.email. CustomerDashboard is never executed.

**Comment by nerfpops** [comment]
Same result with

    let page = Rx.Observable.create(obs => {
        obs.onNext("test")
    })
    return (<div>{page}</div>)

**Comment by garbles** [comment]
please create a PR with a failing spec

**Comment by nerfpops** [comment]
It's very easy to reproduce this issue. I'm just looking into this library and won't spend time figuring out how to create pull requests with failing specs. I'll just check back in a few years instead.

**Comment by LongLiveCHIEF** [comment]
>  ... won't spend time figuring out how to create pull requests with failing specs.

There's your problem right there.  If you knew how to create failing specs, you'd realize the problem isn't with Yolk, it's with your code.  The code you shared isn't even valid javascript.

By writing failing specs, you learn how to code.  Writing failing specs is something that's common to *any* project, and isn't in any particular way unique to this project.

**Comment by nerfpops** [comment]
Alright, since you're basing your argument on the validity of my code, I assume it's due to the return statement - I sincerely apologize for not wrapping the code in a function. I actually had a feeling that you wouldn't be nice to deal with, but I had hoped it was different, because of how great your library is.

**Comment by nerfpops** [comment]
I should probably close this issue.

**Comment by LongLiveCHIEF** [comment]
What I'm trying to say, is that you're inside out.  Data is streamed into your jsx, not the other way around.  

When You use `Observable.create`, then the result is an observable, not a virtual dom element.
