### ISSUE TITLE
Batch updates together

### ISSUE THREAD

**Issue by garbles** [garbles/yolk#17]
If we batch diffing/patching inside of requestAnimationFrame then we can limit the number of attempts to repaint the DOM. I am concerned about race conditions though.

**Comment by jadbox** [comment]
+1

**Comment by garbles** [comment]
#### Notes:

After taking a crack at this and failing, I'm realizing that can't batch updates on a per-component basis - too many race conditions.

As all components are all rooted from `YolkRootComponent`, batch update everything starting from there. We will keep track of the latest changes and patch them in as they are called from the parent?

**Comment by garbles** [comment]
Closing for now. Not #1 on priorities.
