### ISSUE TITLE
Babel 6.0 jsx documentation

### ISSUE THREAD

**Issue by jadbox** [garbles/yolk#30]
After some investigating, I found how to enable jsx tranformations with Yolk for Babel 6. See the below configuration:

Package.json
```
{  
"devDependencies": {
    "babel-core": "^6.0.14",
    "babel-plugin-transform-react-jsx": "^6.0.14",
    "babel-preset-es2015": "^6.0.14"
  },
  "babel": {
    "plugins": [
      [
        "transform-react-jsx",
        {
          "pragma": "Yolk.createElement"
        }
      ]
    ]
  }
}
```

**Comment by garbles** [comment]
I don't think that `babel-loader` is necessary there, but the rest of it yes. Can you submit a PR for this? Add a note to the old stuff about using Babel < 6.0

**Comment by askmatey** [comment]
What are the recommended presets for Babel 6.0 ?

.babelrc
```js
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    "transform-es2015-modules-commonjs",
    [
      "transform-react-jsx", {
        "pragma": "Yolk.createElement"
      }
    ]
  ]
}
```

**Comment by jadbox** [comment]
@askmatey All I use is the "es2015" preset. The others are optional (I don't think "react" preset has any benefit for Yolk afaik).

**Comment by garbles** [comment]
https://github.com/garbles/yolk/pull/58
