### ISSUE TITLE
JSX is very contentious

### ISSUE THREAD

**Issue by kumavis** [garbles/yolk#32]
programmers either love it or hate it.
I would recommend showing a short example on using [virtual-hyperscript](https://github.com/Matt-Esch/virtual-dom/tree/master/virtual-hyperscript) as an alternative.

**Comment by kumavis** [comment]
this may make it easier
https://github.com/mlmorg/react-hyperscript

**Comment by garbles** [comment]
I totally agree, it's a pretty polarizing issue. Problem is I'm using a [forked version of virtual-dom](https://github.com/yolkjs/yolk-virtual-dom) for various reasons:

1) With JSX I don't need tag parsing, so I removed it. This actually results in a pretty nice performance increase, but you can't do something like `Yolk.createElement("div#some-id.my-class", ...)` anymore.
2) Didn't need thunks
3) Needed more customizability on widgets
4) Issues on the main repo haven't been addressed for months, so I'm assuming that it's dead

That said, I'd definitely welcome an PR which exposes `Yolk.h` to the public interface (similar to the React example you've linked to above).

**Comment by garbles** [comment]
Also open to other suggestions! :family: 

PS, cute baby

**Comment by jadbox** [comment]
@kumavis How much did @staltz pay you to submit this? (I'm kidding!)

JSX seems to be the path of least resistance, but it would be nice to support other methods in the future like HS.

**Comment by staltz** [comment]
> @kumavis How much did @staltz pay you to submit this? (I'm kidding!)

1000€

> 1) With JSX I don't need tag parsing, so I removed it.

With an approach like https://github.com/ohanhi/hyperscript-helpers you can avoid tag parsing, and it's actually nicer than VH.

**Comment by kumavis** [comment]
> 1) With JSX I don't need tag parsing, so I removed it. This actually results in a pretty nice performance increase

ah interesting. that is a legit concern. seems like an optional tag parsing layer, that could benefit from a pre-build step would be the right way to go.

> 3) Needed more customizability on widgets

can you expand on or link to what additional concerns you had to accommodate?

> 4) Issues on the main repo haven't been addressed for months, so I'm assuming that it's dead

oh. I haven't been keeping up. surprises me, I much prefer a DSL over writing fake html in js :smiling_imp:. surprised its not more popular.

> 1000€

@jadbox @staltz sorry i've moved on to cryptocurrencies, and i'm not backwards compatible ; )

> With an approach like https://github.com/ohanhi/hyperscript-helpers you can avoid tag parsing

this would benefit nicely from the `with(hh)` keyword, where available.

```js
with(hh) {
  return div( [
    h1( ... ),
    h2( ... ),
    h3( ... ),
  ] )
}
```

**Comment by garbles** [comment]
> can you expand on or link to what additional concerns you had to accommodate?

A virtual-dom Widget's destroy function is called after the node has been removed from the DOM. I wanted an extra hook for just before it's been removed. Ended up calling it [`predestroy`](https://github.com/yolkjs/yolk-virtual-dom/blob/master/vdom/patch-op.js#L40-L46). Following this thinking I'd also like to add another hook for just after it's been inserted into the DOM so that I can [remove this hack](https://github.com/yolkjs/yolk/blob/master/src/mountable.js#L4-L15).

**Comment by garbles** [comment]
https://github.com/garbles/yolk/pull/42
