### ISSUE TITLE
Use lodash helpers

### ISSUE THREAD

**Issue by askmatey** [garbles/yolk#41]
Are there any reasons not to replace the existing utilities with lodash methods?

- `isDefined.js` Lodash/Lang equivalent to [`_.isUndefined`](https://lodash.com/docs#isUndefined)
- `isEmpty.js` equivalent to Lodash/Lang [`_.isUndefined`](https://lodash.com/docs#isEmpty)
- `isFunction.js` equivalent to Lodash/Lang [`_.isFunction`](https://lodash.com/docs#isFunction)
- `isNumber.js` equivalent to Lodash/Lang [`_.isNumber`](https://lodash.com/docs#isNumber)
- `isString.js` equivalent to Lodash/Lang [`_.isString`](https://lodash.com/docs#isString)

**Comment by garbles** [comment]
Because they seem like unnecessary dependencies.

**Comment by jadbox** [comment]
My 2 cents: if we start needing more than 5-10 utilities helpers that Lodash supports, might as well use it. As is, I think it's fine to not need to rely on Lodash. (Btw, lodash-fp is better for stream related work)

**Comment by garbles** [comment]
:dancer: definitely not interested in depending on the entire lodash library. In fact, `kababcase and `camelcase` can probably be removed with a little work. `isplainobject` is seriously doing some magic shit and the only one I feel that needs to stay.

**Comment by askmatey** [comment]
- :white_check_mark:  Replace ~~`isPlainObject`~~

[rackt/redux](https://github.com/rackt/redux) uses a simple approach, to implement an `isPlainObject` function for reducers. Abracadabra.

```js
var fnToString = (fn) => Function.prototype.toString.call(fn)
var objStringValue = fnToString(Object)

export default function isPlainObject(obj) {
  if (!obj || typeof obj !== 'object') {
    return false
  }

  var proto = typeof obj.constructor === 'function' ? Object.getPrototypeOf(obj) : Object.prototype

  if (proto === null) {
    return true
  }

  var constructor = proto.constructor

  return typeof constructor === 'function'
    && constructor instanceof constructor
    && fnToString(constructor) === objStringValue
}
```

See: https://github.com/rackt/redux/blob/master/src/utils/isPlainObject.js

**Comment by askmatey** [comment]
-  :white_check_mark:  Replace ~~`kebabCase`~~

The `kebabCase` implementation of lodash splits numeric values into separate words. This is an issue for me, since I need to use data-* attributes like `data-l10n-id` for my project.

```js
console.log(_.kebabCase('dataL10nId')); // data-l-10-n-id, expected data-l10n-id
```

Example:

```js
function kebabize(str) {
  return str.replace(/(?:^\w|[A-Z]|\b\w)/g, function(letter, index) {
    return index == 0 ? letter : '-' + letter.toLowerCase()
  }).replace(/\s+/g, '');
}

console.log(kebabize('dataL10nId')); // data-l10n-id
console.log(kebabize('dataBoxValue')); // data-box-value
console.log(kebabize('ariaHidden')); //aria-hidden
```

Demo: https://jsfiddle.net/2xwpe60j/

**Comment by garbles** [comment]
:white_check_mark: :white_check_mark: :white_check_mark: 

@askmatey if you submit a PR with these changes + unit tests and everything still passes then yeaaa.

**Comment by askmatey** [comment]
Yes, I will submit a PR on the weekend

**Comment by garbles** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by askmatey** [comment]
See #47
