### ISSUE TITLE
Component props auto distinctUntilChanged

### ISSUE THREAD

**Issue by jadbox** [garbles/yolk#50]
With the large application we are building, we are noticing a lot of time is spent when state changes, but does not affect much of the actual drawing to the DOM. Would it make sense to make every property passed into a component have its stream added to distinctUntilChanged to only update logic within those components when a different-from-the-last value arrives? Just a thought.

**Comment by garbles** [comment]
Oh! That's coming. I have a local branch that does exactly this, though I haven't pushed it because I'm not happy with the code yet.

**Comment by jadbox** [comment]
Neat! Please update here when it's done. In the meantime, I wrote these utils for my project:

```
RxObserverProto.getProp = function(prop, selector) {
  return this.map(x=>x.toJS?x.get(prop):x[prop]).filter(x=>x!==null)
                          .distinctUntilChanged().map(selector || (x=>x));
}

RxObserverProto.getPropIn = function(props, selector) {
  return this.map(x=>x.getIn?x.getIn(props):getIn(x, props)).filter(x=>x!==null)
        .distinctUntilChanged()
        .map(selector || (x=>x));
}
```
```
RxObserverProto.combineProps = function(keys, selector) {
  const obs = _.map(keys, k => this.getProp(k) );
  return Rx.Observable.combineLatest(obs, selector);
}
```

**Comment by garbles** [comment]
Done here: https://github.com/garbles/yolk/pull/51

Base components will only re-render when a prop actually changes. I don't think it's a good idea to use `distinctUntilChanged` at higher levels because it does a deep equal check, so passing in and checking a complex data-tree at the root is very slow.

If you're requiring something else, it might be a good idea to consider a higher-order function that wraps your components. For example,

```js
const Component = pureRender(function Comp (props) {
  // ...
})
```

**Comment by jadbox** [comment]
@garbles Where do you see that distinctUntilChanged does a deep equal check? I am under the impression that distinct is more expensive as it keeps a history of all previous values. Wouldn't just Distinct cause bugs since you most likely want to rerender the component when a value has changed, yet as been seen before. E.g:
```
A => B => C => A
```
Wouldn't you would want to rerender the later 'A' state even though it's been seen in the past?

**Comment by garbles** [comment]
https://github.com/garbles/yolk/blob/master/test/unit/CompositePropSubject-test.js#L109-L132

**Comment by garbles** [comment]
> Where do you see that distinctUntilChanged does a deep equal check?

If it didn't do a deep equal check, then it would be very dangerous to use anyway.
