### ISSUE TITLE
wrapObject headaches

### ISSUE THREAD

**Issue by jadbox** [garbles/yolk#56]
In our usecase, we need to pass a very large objects around (generated by state changes) into sub yolk components. However, I'm seeing a 17 second pause in our application due to Yolk WrapObject iterating through every property of these large objects to wrap them into Rx. It looks like the only exception is an Immutable object, but ideally I don't want to convert these objects to Immutable... because they are large. The only work around I see is to convert the shallow level of our object to Immutable and then toJS() them inside of the sub component.

Any thoughts on an optimal solution? Perhaps we can add a special property "data-" like property that does not get subjected to (deep/recursive) object wrapping?

**Comment by garbles** [comment]
Haha wow. How many properties do these objects have?

I'm not keen on adding special properties in order to increase performance.

**Comment by jadbox** [comment]
We're talking something like 30,000 nested properties/values. Our use-case is a comprehensive metric-driven dashboard so there's a lot of data passing here.

The only other option I see is to make a Yolk property (somewhere) that tells WrapObject to not bother with deep wrapping. Otherwise, we are forced to put this data into a singleton to sub components... although that subverts the "proper" way of passing data explicitly.

**Comment by garbles** [comment]
Crazy. A agree with you, but for now you can avoid deep wrapping by adding a function `toJS` to the root of the object.

**Comment by garbles** [comment]
I'm going to allow `wrapObject` to be pluggable so that you can define thinks on your own.

**Comment by jadbox** [comment]
:dancers:

**Comment by garbles** [comment]
@jadbox @0.10.1 exposes `wrapObject` so that you can override it.

```js
const oldWO = Yolk.wrapObject

Yolk.wrapObject = function (obj, opts) {
  if (myCondition(obj)) {
    return Rx.Observable.just(obj)
  }

  return oldWO(obj, opts)
}
```

Currently not documented, but I really need to do something about documentation soon.
