### ISSUE TITLE
Update JSX Advice for Babel 6

### ISSUE THREAD

**Issue by KenPowers** [garbles/yolk#57]
[Babel 6 changed a lot of things](http://babeljs.io/blog/2015/10/29/6.0.0/), including [JSX transformation](http://babeljs.io/docs/plugins/transform-react-jsx/).

I haven't actually tried it yet, so I didn't want to submit a pull request, but I thought it would be good to open this issue for the sake of awareness.

This should be the new configuration (again, haven't tried it yet):

```json
{
  "plugins": [
    ["transform-react-jsx", { "pragma": "Yolk.h" }]
  ]
}
```

We'll also have to document that [`babel-plugin-transform-react-jsx`](https://www.npmjs.com/package/babel-plugin-transform-react-jsx) will have to be installed as a dev dependency.

I would also suggest removing the `package.json` option. It was nice to have but I've never seen it actually used anywhere, people tend to stick to `.babelrc`.

**Comment by garbles** [comment]
Yea I agree. If you submit a PR I'll merge pretty quick.

**Comment by KenPowers** [comment]
Would you prefer to have Babel 5 instructions as well? Or would you like to pave the way for the future and only have Babel 6 instructions?

**Comment by garbles** [comment]
Get rid of Babel 5 as it is not being maintained.

**Comment by KenPowers** [comment]
I'll take a look at this when I get home today.
