### ISSUE TITLE
Use composition instead of inheritance for custom components

### ISSUE THREAD

**Issue by garbles** [garbles/yolk#61]
Right now in order to create a custom component, one must inherit from `Yolk.CustomComponent`. Should change this so that I can pass in an object to a function. For example,

```js
const schema = {
  onMount (props, node) { ... },
  onUpdate (props, node) { ... },
  onUnmount (node) { ... }
}

const MyComponent = Yolk.createCustomComponent(schema)
```

**Comment by f5io** [comment]
You are probably already aware of this, but simply exposing `CustomComponent.extend` as `createCustomComponent` will work. [See this gist](https://gist.github.com/f5io/91816c9b41ac196e3fc4#file-yolk-create-custom-component-js-L3)

I like the idea of giving the developer the choice between composition or classical inheritance.

**Comment by garbles** [comment]
Yup! Thanks for the input. I haven't done anything about this yet because I've been busy, but you're definitely right. :family:

**Comment by garbles** [comment]
Going to close because I've just merge the full rewrite branch.
