### ISSUE TITLE
Simplify parsing props

### ISSUE THREAD

**Issue by garbles** [garbles/yolk#64]
Allowing props to be infinitely nested observables, or arrays/objects of observables was a cool idea, but this creates a huge performance bottle neck. I'd like to remove this. The prop should either be an observable - pass it right though to the next component - or it should be a non-observable - then wrapped in `Rx.Observable.just`.

This will obviously create massive breaking changes. In light of this, I'm considering a rewrite using TypeScript and replacing `virtual-dom` with a faster equivalent.

**Comment by oskbor** [comment]
If you are thinking about a rewrite, perhaps you could consider using the rxjs 5.0 beta as well. https://github.com/ReactiveX/RxJS

**Comment by garbles** [comment]
should have mentioned that. will definitely be using Rx5.

I should also note that the outward facing API won't change.

**Comment by garbles** [comment]
Being worked on here https://github.com/garbles/yolk/pull/67
