### ISSUE TITLE
Question: what is your dev toolchain like ?

### ISSUE THREAD

**Issue by deanius** [garbles/yolk#66]
I presume you have a browserify-based workflow, but, since I can't simply source yolk from cdnjs.com yet, I wonder if you could explain how you create a distribution file from this project, or where one is posted, and if it's usable that way. TIA,

Dean

**Comment by garbles** [comment]
Aye, it's not cdnjs, but it is on npmcdn! https://npmcdn.com/yolk@0.10.1/dist/yolk.js

I'm currently in the middle of a rewrite and I'm using webpack instead. (The outward facing API won't change too much).

If you are still interested in building a local copy, it's just `npm run bundle`

**Comment by deanius** [comment]
Thanks !

**Comment by deanius** [comment]
I'm having trouble reading the distributed file - what are the top-level exports ? I see `h` and `render` but when I source that file in this jsbin, I see no top-level `yolk`, nor are `h` and `render` defined on the global object..

**Comment by deanius** [comment]
Never mind- I see that it's `window.Yolk` - thanks !

**Comment by garbles** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by deanius** [comment]
Just curious - do you know why I'd get `Uncaught TypeError: Cannot read property 'children' of undefined` in this attempted port of the Counter example to a JSBin ?

http://jsbin.com/wesopa/4/edit?html,js,console,output ?

**Comment by garbles** [comment]
haha two problems.

First, one is that babel automatically transpiles JSX to `React.createElement` and because you can't change this on JSBin, you must override the function by adding this to your HTML tab

```html
<script>
  var React = { createElement: Yolk.h };
</script>
```
(Normally, you would just set this value in your `.babelrc`.)

Second, Your HTML tab has invalid markup. `<div id="container"/>` should be `<div id="container"></div>`

**Comment by deanius** [comment]
Hey, Thanks ! That self-closing div didn't work in raw HTML was a suprise to me - but the explanation of `createElement` makes sense. It works now !
