### ISSUE TITLE
Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by jadbox** [garbles/yolk#68]
Recently, I've started getting this error when components (seems to be elements created through registerElement) are removed from the DOM. Any idea?
```
Cannot read property 'dispose' of undefined
destroy	@	YolkBaseComponent.js:69
destroy	@	YolkBaseComponent.js:77
YolkCompositeFunctionWrapper.destroy	@	YolkCompositeFunctionWrapper.js:35
destroy	@	YolkCompositeComponent.js:48
detachedCallback	@	registerElement.js:22
```

**Comment by garbles** [comment]
Can you repro with a test / jsbin?

**Comment by jadbox** [comment]
It seems like when a component is instanced and very quickly removed from the DOM... perhaps it never finished instantiating. In the meantime, we've worked around the issue. Going to close this for now as the add-and-immediately-remove is probably an odd use-case anyway.

**Comment by garbles** [comment]
Please let me know if it comes up again.
