### ISSUE TITLE
Better way to organize actions

### ISSUE THREAD

**Issue by jadbox** [garbles/yolk#69]
Looking at the Todo Example for handling actions (https://github.com/yolkjs/yolk-todomvc/blob/master/js/TodoActions.js), it seems like there should be a better way to organize actions. In our own app, our actions controller has grown exponentially. Is there a way to use Cycle style system to pass the actions a components requires into it as a form of parameter? This helps subdivide the controllers into smaller pieces and also removes the hard-coded connection between view components and controllers. For unit testing, this is also preferable as currently by convention, the view components directly call functions on the Actions (singleton) object. Thoughts?

**Comment by garbles** [comment]
I plan to address this issue with v1. Observables/Subjects won't be wrapped when passed in as props

**Comment by garbles** [comment]
Going to close because I've just merge the full rewrite branch.
