### ISSUE TITLE
Cannot get onMount events to fire

### ISSUE THREAD

**Issue by geekytime** [garbles/yolk#79]
I've been trying to use the new onMount event to instantiate a Jquery widget, but I can't get the onMount event to fire at all.

I've tried specifying my `onMount` handler in both JSX, and `h`. The component renders, but I never get into the code where I subscribe to handleMount$.

```
module.exports = function({createEventHandler}){
  var handleMount$ = createEventHandler();

  handleMount$.subscribe(function(){
    console.log("onMount", arguments);
  });

  return (
     <div onMount={handleMount$} className="FOO">
       Test content
     </div>
  );
};
```

Is there something that I'm missing about the onMount event? I dug through the code, but I haven't been able to figure it out. Any help would be appreciated.

**Comment by geekytime** [comment]
It looks like [this line in Mountable](https://github.com/garbles/yolk/blob/master/lib/mountable.js#L16) might be the problem? 

```
if ((0, _is.isFunction)(fn) && node.parentNode) {
```

It's returning false, even though `fn` is set to a `Subject` for that component.

**Comment by garbles** [comment]
Yup. That is a bug. `VirtualNode` should pass in `fn.next` if `fn` is a subject.

Feel free to submit a PR; otherwise I'll take care of it later.

**Comment by geekytime** [comment]
I was trying to submit a PR when I bumped up against #80.

I'll come at it debugging it from a different angle and try to submit a PR tomorrow morning.

**Comment by garbles** [comment]
https://github.com/garbles/yolk/pull/81 should fix this. test for this was using functions.

**Comment by geekytime** [comment]
Thanks. This fixed it.

**Comment by garbles** [comment]
:tada:
