### ISSUE TITLE
`npm link yolk` breaks `import "rxjs/add/operator/{operator}` syntax for some webpack builds

### ISSUE THREAD

**Issue by geekytime** [garbles/yolk#80]
I was trying to `npm link yolk` into my project so I could submit a PR for yolk, and I started getting errors that rxjs Observable functions such as `startWith` didn't exist, even though I had imported them via the `rxjs/add/operator` approach. Everything works fine if I unlink and reinstall yolk, but as soon as I link in Yolk, the Observables given to me by Yolk no longer include the "added" operators.

I tried modifying the `package.json` file for Yolk to set `"main":"src/index.js" instead of `"lib/index.js`, in the hopes that webpack was getting confused and registering two modules for `Observable`, but it didn't help.

When I dug into the code for my compiled bundle, it appears that `Observable` is being registered as a module by webpack multiple times, but I'm not sure why, and I'm not sure why it only happens when I `npm run link` the projects together.

I've included a zip file of a test project that recreates the problem on my Mac.

[yolk-test.zip](https://github.com/garbles/yolk/files/215765/yolk-test.zip)

I realize that this could be a problem with my webpack config, but this being a vanilla project, it seems like it should at least be documented why some projects might have trouble linking in Yolk for testing pull requests.

**Comment by garbles** [comment]
I'm assuming that this probably has something to do with Yolk using a different version of Rx than you're using. Are you using npm 3 + same version of RxJS v5 beta?

I'll take a closer look at this later.

**Comment by garbles** [comment]
Whoops. Didn't mean to close this.

**Comment by geekytime** [comment]
> this probably has something to do with Yolk using a different version of Rx than you're using

I completely uninstalled Rx and was just using the one installed by Yolk. I also tried explicitly installing the same version Yolk uses, but that didn't help either. As soon as I `npm link yolk`, I start seeing the double-entries in WebPack.

It might honestly be a bug (or hidden feature) in WebPack, but I thought it was worth mentioning here because it was making it difficult for me to test Yolk changes in my app. I'll put WebPack in debug mode and mess around with it a bit more this morning.

**Comment by geekytime** [comment]
Yeah, [there are definitely problems with WebPack and symlinks](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=webpack%20duplicate%20npm%20link).

**Comment by geekytime** [comment]
So I read through several issues around Webpack and symlinks, and finally found [this solution](https://github.com/webpack/webpack/issues/966#issuecomment-95491120), which works for me.

The problem is that Webpack sees the symlinked rxjs directory in Yolk as a different version of rxjs, and registers two copies of the library in the bundle. For most modules this doesn't matter much, but because rxjs is augmented at run time, it breaks. Yolk is creating a non-augmented Observable instance, and handing it back to my code, which is expecting an augmented Observable instance.

The simplest solution seems to be to `npm link` my project's version of rxjs into Yolk, so Webpack resolves the same real path to rxjs for both my project and for Yolk. As long as `rxjs` points to the same real path for everything in the bundle, it seems to work.
