### ISSUE TITLE
Is there still a distribution being published for use from JSBin?

### ISSUE THREAD

**Issue by geekytime** [garbles/yolk#84]
It looks like there maybe used to be a distribution we could access through rawgit, but it's not there anymore. I didn't see anything in the current build that looks like that dist file.

**Comment by garbles** [comment]
Yup nothing exists yet. Working on it!

**Comment by geekytime** [comment]
I'd like to get this working. Would you be okay with using Webpack to build the distributable bundle?

**Comment by geekytime** [comment]
I noticed that webpack was already in the dev dependencies, so I just knocked this out quickly. Hopefully it'll work.

**Comment by garbles** [comment]
https://npmcdn.com/yolk@1.0.0-beta.6/dist/yolk.js
