### ISSUE TITLE
JSX: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by jadbox** [garbles/yolk#95]
If a jsx parameter results in a `null` value, the old behavior was that nothing would be rendered for it. Now, I get `Cannot read property 'toString' of null` for that jsx parameter. Is this an intentional change?

**Comment by garbles** [comment]
If you submit a PR with a failing test for this case then it will be easier for me to fix.

**Comment by jadbox** [comment]
I'll try. It seems simple enough to reproduce for us as it's any stream value resulting to `null` to a jsx parameter.

Like:
```
const r$ = Rx.Observable.of(null);
return (
<div>r$</div>
)
```

**Comment by jadbox** [comment]
Stack:
```
Rx.umd.js:1413 Uncaught TypeError: Cannot read property 'toString' of undefined

wrap @ wrapText.js:22wrapText @ wrapText.js:26
MapSubscriber._next @ Rx.umd.js:8071
Subscriber.next @ Rx.umd.js:1272
MapSubscriber._next @ Rx.umd.js:8077
Subscriber.next @ Rx.umd.js:1272
SwitchMapSubscriber.notifyNext @ Rx.umd.js:10402
```

**Comment by jadbox** [comment]
I've submitted a PR that fixes the issue for us :)
